language: node_js
node_js:
  - "6.9"
services:
 - mongodb
before_script:
  - npm install
script:
  - npm test
sudo: false
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info